name: C

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./c

        steps:
            - uses: actions/checkout@v4
            - uses: johelegp/gcc-snapshot@v1
            - name: Install GCC Snapshot
              uses: johelegp/gcc-snapshot@v1
              with:
                  cache: false # Disable caching to avoid 422 error
            - name: Build
              run: make
            - name: Run tests
              run: make test
