name: C

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./c

        steps:
            - uses: actions/checkout@v4
            - name: Install build dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gcc
            - name: Build
              run: make
            - name: Run tests
              run: make test
