name: golang-checks
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    golangci:
        name: Lint and Test
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./go
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
                  cache-dependency-path: |
                      **/go.sum
                      go.work

            - name: Install golangci-lint
              run: go install github.com/golangci/golangci-lint@v2.1.2

            - name: Sync workspace
              run: go work sync

            - name: Run golangci-lint
              run: |
                  find . -name go.mod -not -path "./go.mod" | while read modfile; do
                    dir=$(dirname "$modfile")
                    echo "🛠️ Linting $dir"
                    (cd "$dir" && golangci-lint run --out-format=github-actions ./...)
                  done

            - name: Run tests
              run: |
                  find . -name go.mod -not -path "./go.mod" | while read modfile; do
                    dir=$(dirname "$modfile")
                    echo "🧪 Testing $dir"
                    (cd "$dir" && go test -v -race ./...)
                  done
